.rnew gsc_record__define.pro
.rnew gsc_region__define.pro
.rnew sao_record__define.pro
.rnew str_aberr_pos.pro
.rnew str_aberr_radec.pro
.rnew strcat_get_inputs.pro
.rnew strcat_gsc_input.pro
.rnew strcat_input.pro
.rnew strcat_nbright.pro
.rnew strcat_sao_input.pro
.rnew strcat_tycho2_input.pro
.rnew strcat_tycho_input.pro
.rnew strcat_ucact_input.pro
.rnew tycho_record__define.pro
.rnew tycho_region__define.pro
.rnew ucact_directory__define.pro
.rnew ucact_header__define.pro
.rnew ucact_packed_star__define.pro
.rnew ucact_record__define.pro
.rnew ucact_star__define.pro
@compile_gsc2
