.rnew detect_cas.pro
.rnew detect_cas_uvis.pro
.rnew detect_ctio.pro
.rnew detect_dawn.pro
.rnew detect_dh.pro
.rnew detect_ext.pro
.rnew detect_fits.pro
.rnew detect_gll.pro
.rnew detect_map.pro
.rnew detect_mask.pro
.rnew detect_mirac.pro
.rnew detect_multi.pro
.rnew detect_occ.pro
.rnew detect_pds.pro
.rnew detect_spdr.pro
.rnew detect_tdl.pro
.rnew detect_vgr_cd.pro
.rnew detect_vgr_pps.pro
.rnew detect_vgr.pro
.rnew detect_vgr_rss.pro
.rnew detect_vicar.pro
