.rnew class_copy_descriptor.pro
.rnew classes_get.pro
.rnew class_evolve.pro
.rnew class_extract.pro
.rnew class_get_abbrev.pro
.rnew class_get_field_names.pro
.rnew class_get_field.pro
.rnew class_get_method.pro
.rnew class_get.pro
.rnew class_get_tree.pro
.rnew class_homogenize.pro
.rnew class_insert.pro
.rnew class_search.pro
.rnew class_set_field.pro
.rnew clget.pro
.rnew clset.pro
