; minas compilation script
.rnew grim
.rnew plod
.rnew ./debug/bcode.pro
.rnew ./debug/ext_test/ext_test.pro
.rnew ./debug/idl_string_test/idl_string_test.pro
.rnew ./debug/lic/lic_gen.pro
.rnew ./debug/lic/lic_override.pro
.rnew ./debug/lic/lic_read_proto.pro
.rnew ./debug/lic/lic_write.pro
.rnew ./debug/memtest.pro
.rnew ./debug/read_isisres.pro
.rnew ./debug/test_loadck.pro
.rnew ./nv/com/pg/pg_blemish.pro
.rnew ./nv/com/pg/pg_center.pro
.rnew ./nv/com/pg/pg_chisq.pro
.rnew ./nv/com/pg/pg_cntrd.pro
.rnew ./nv/com/pg/pg_coregister.pro
.rnew ./nv/com/pg/pg_covariance.pro
.rnew ./nv/com/pg/pg_cursor.pro
.rnew ./nv/com/pg/pg_cvchisq.pro
.rnew ./nv/com/pg/pg_cvscan_coeff.pro
.rnew ./nv/com/pg/pg_cvscan.pro
.rnew ./nv/com/pg/pg_despike.pro
.rnew ./nv/com/pg/pg_disk.pro
.rnew ./nv/com/pg/pg_drag.pro
.rnew ./nv/com/pg/pg_draw.pro
.rnew ./nv/com/pg/pg_edges.pro
.rnew ./nv/com/pg/pg_farfit.pro
.rnew ./nv/com/pg/pg_fit.pro
.rnew ./nv/com/pg/pg_free.pro
.rnew ./nv/com/pg/pg_get_cameras.pro
.rnew ./nv/com/pg/pg_get_maps.pro
.rnew ./nv/com/pg/pg_get_planets.pro
.rnew ./nv/com/pg/pg_get_rings.pro
.rnew ./nv/com/pg/pg_get_stars.pro
.rnew ./nv/com/pg/pg_get_station.pro
.rnew ./nv/com/pg/pg_grid_disk.pro
.rnew ./nv/com/pg/pg_grid_globe.pro
.rnew ./nv/com/pg/pg_grid.pro
.rnew ./nv/com/pg/pg_hide_disk.pro
.rnew ./nv/com/pg/pg_hide_globe.pro
.rnew ./nv/com/pg/pg_hide_limb.pro
.rnew ./nv/com/pg/pg_hide.pro
.rnew ./nv/com/pg/pg_limb.pro
.rnew ./nv/com/pg/pg_linearize_image.pro
.rnew ./nv/com/pg/pg_map.pro
.rnew ./nv/com/pg/pg_mosaic.pro
.rnew ./nv/com/pg/pg_move.pro
.rnew ./nv/com/pg/pg_nearest_points.pro
.rnew ./nv/com/pg/pg_northangle.pro
.rnew ./nv/com/pg/pg_photom.pro
.rnew ./nv/com/pg/pg_points.pro
.rnew ./nv/com/pg/pg_profile_ring.pro
.rnew ./nv/com/pg/pg_ptassoc.pro
.rnew ./nv/com/pg/pg_ptchisq.pro
.rnew ./nv/com/pg/pg_ptcntrd.pro
.rnew ./nv/com/pg/pg_ptfarscan.pro
.rnew ./nv/com/pg/pg_ptscan_coeff.pro
.rnew ./nv/com/pg/pg_ptscan.pro
.rnew ./nv/com/pg/pg_put_cameras.pro
.rnew ./nv/com/pg/pg_put_maps.pro
.rnew ./nv/com/pg/pg_put_planets.pro
.rnew ./nv/com/pg/pg_put_rings.pro
.rnew ./nv/com/pg/pg_put_stars.pro
.rnew ./nv/com/pg/pg_range.pro
.rnew ./nv/com/pg/pg_repoint.pro
.rnew ./nv/com/pg/pg_resfit.pro
.rnew ./nv/com/pg/pg_residuals.pro
.rnew ./nv/com/pg/pg_resloc.pro
.rnew ./nv/com/pg/pg_ring_sector.pro
.rnew ./nv/com/pg/pg_rm_disk.pro
.rnew ./nv/com/pg/pg_rm_globe.pro
.rnew ./nv/com/pg/pg_select_points.pro
.rnew ./nv/com/pg/pg_select.pro
.rnew ./nv/com/pg/pg_select_region.pro
.rnew ./nv/com/pg/pg_shadow_disk.pro
.rnew ./nv/com/pg/pg_shadow_globe.pro
.rnew ./nv/com/pg/pg_shadow.pro
.rnew ./nv/com/pg/pg_strip.pro
.rnew ./nv/com/pg/pg_str_limit_mag.pro
.rnew ./nv/com/pg/pg_sub_body.pro
.rnew ./nv/com/pg/pg_threshold.pro
.rnew ./nv/com/pg/pg_to_disk.pro
.rnew ./nv/com/pg/pg_to_surface.pro
.rnew ./nv/com/pg/pg_trim.pro
.rnew ./nv/com/pg/pg_vectors.pro
.rnew ./nv/com/pg/sub/pg_fit_coeff_struct__define.pro
.rnew ./nv/com/pg/sub/pg_points_struct__define.pro
.rnew ./nv/com/pg/sub/pgs_cat_points.pro
.rnew ./nv/com/pg/sub/pgs_cat_ps.pro
.rnew ./nv/com/pg/sub/pgs_cat_vectors.pro
.rnew ./nv/com/pg/sub/pgs_clone_gd.pro
.rnew ./nv/com/pg/sub/pgs_clone_ps.pro
.rnew ./nv/com/pg/sub/pgs_count_descriptors.pro
.rnew ./nv/com/pg/sub/pgs_cull.pro
.rnew ./nv/com/pg/sub/pgs_gd.pro
.rnew ./nv/com/pg/sub/pgs_idp_to_gd.pro
.rnew ./nv/com/pg/sub/pgs_idp_to_ps.pro
.rnew ./nv/com/pg/sub/pgs_include.pro
.rnew ./nv/com/pg/sub/pgs_make_gd.pro
.rnew ./nv/com/pg/sub/pgs_name_sort.pro
.rnew ./nv/com/pg/sub/pgs_npoints.pro
.rnew ./nv/com/pg/sub/pgs_null.pro
.rnew ./nv/com/pg/sub/pgs_points.pro
.rnew ./nv/com/pg/sub/pgs_points_ps.pro
.rnew ./nv/com/pg/sub/pgs_read_ps.pro
.rnew ./nv/com/pg/sub/pgs_set_points.pro
.rnew ./nv/com/pg/sub/pgs_size.pro
.rnew ./nv/com/pg/sub/pgs_sn_to_gd.pro
.rnew ./nv/com/pg/sub/pgs_trim_invisible_points.pro
.rnew ./nv/com/pg/sub/pgs_valid.pro
.rnew ./nv/com/pg/sub/pgs_visible_points.pro
.rnew ./nv/com/pg/sub/pgs_write_ps.pro
.rnew ./nv/gr/brim.pro
.rnew ./nv/gr/grim_colortool.pro
.rnew ./nv/gr/grim_mag_cursor.pro
.rnew ./nv/gr/grim_message.pro
.rnew ./nv/gr/grim_no_cursor.pro
.rnew ./nv/gr/grim_overlay_settings.pro
.rnew ./nv/gr/grim_pixel_readout.pro
.rnew ./nv/gr/grim_plane_settings.pro
.rnew ./nv/gr/grim_print.pro
.rnew ./nv/gr/grim.pro
.rnew ./nv/gr/grim_rc_settings.pro
.rnew ./nv/gr/grim_readout_cursor.pro
.rnew ./nv/gr/grim_user_mode_struct__define.pro
.rnew ./nv/gr/interface/gr_draw.pro
.rnew ./nv/gr/interface/ingrid.pro
.rnew ./nv/gr/plod/oplod.pro
.rnew ./nv/gr/plod/plod_print.pro
.rnew ./nv/gr/plod/plod.pro
.rnew ./nv/gr/tools/gr_lsqtool.pro
.rnew ./nv/gr/tools/gr_maptool.pro
.rnew ./nv/gr/tools/gr_phttool.pro
.rnew ./nv/lib/bod/bod_avel.pro
.rnew ./nv/lib/bod/bod_body_to_inertial_pos.pro
.rnew ./nv/lib/bod/bod_body_to_inertial.pro
.rnew ./nv/lib/bod/bod_body_to_radec.pro
.rnew ./nv/lib/bod/bod_clone_descriptor.pro
.rnew ./nv/lib/bod/bod_copy_descriptor.pro
.rnew ./nv/lib/bod/bod_core.pro
.rnew ./nv/lib/bod/_bod_evolve.pro
.rnew ./nv/lib/bod/bod_evolve.pro
.rnew ./nv/lib/bod/bod_inertial.pro
.rnew ./nv/lib/bod/bod_inertial_to_body_pos.pro
.rnew ./nv/lib/bod/bod_inertial_to_body.pro
.rnew ./nv/lib/bod/bod_init_descriptors.pro
.rnew ./nv/lib/bod/bod_ndv.pro
.rnew ./nv/lib/bod/bod_orient.pro
.rnew ./nv/lib/bod/bod_orientt.pro
.rnew ./nv/lib/bod/bod_pos.pro
.rnew ./nv/lib/bod/bod_radec_to_body.pro
.rnew ./nv/lib/bod/bod_replicate.pro
.rnew ./nv/lib/bod/bod_set_avel.pro
.rnew ./nv/lib/bod/bod_set_orient.pro
.rnew ./nv/lib/bod/bod_set_pos.pro
.rnew ./nv/lib/bod/bod_set_time.pro
.rnew ./nv/lib/bod/bod_set_vel.pro
.rnew ./nv/lib/bod/bod_time.pro
.rnew ./nv/lib/bod/bod_vel.pro
.rnew ./nv/lib/bod/body_descriptor__define.pro
.rnew ./nv/lib/cam/cam_body.pro
.rnew ./nv/lib/cam/cam_body_to_focal.pro
.rnew ./nv/lib/cam/cam_clone_descriptor.pro
.rnew ./nv/lib/cam/cam_copy_descriptor.pro
.rnew ./nv/lib/cam/camera_descriptor__define.pro
.rnew ./nv/lib/cam/_cam_evolve.pro
.rnew ./nv/lib/cam/cam_evolve.pro
.rnew ./nv/lib/cam/cam_exposure.pro
.rnew ./nv/lib/cam/cam_fn_data_p.pro
.rnew ./nv/lib/cam/cam_fn_focal_to_image.pro
.rnew ./nv/lib/cam/cam_fn_image_to_focal.pro
.rnew ./nv/lib/cam/cam_focal_to_body.pro
.rnew ./nv/lib/cam/cam_focal_to_image_linear.pro
.rnew ./nv/lib/cam/cam_focal_to_image_poly.pro
.rnew ./nv/lib/cam/cam_focal_to_image.pro
.rnew ./nv/lib/cam/cam_focal_to_image_radial.pro
.rnew ./nv/lib/cam/cam_get_poly_matrices.pro
.rnew ./nv/lib/cam/cam_image_to_focal_linear.pro
.rnew ./nv/lib/cam/cam_image_to_focal_poly.pro
.rnew ./nv/lib/cam/cam_image_to_focal.pro
.rnew ./nv/lib/cam/cam_image_to_focal_radial.pro
.rnew ./nv/lib/cam/cam_init_descriptors.pro
.rnew ./nv/lib/cam/cam_nx.pro
.rnew ./nv/lib/cam/cam_ny.pro
.rnew ./nv/lib/cam/cam_oaxis.pro
.rnew ./nv/lib/cam/cam_reorient.pro
.rnew ./nv/lib/cam/cam_replicate.pro
.rnew ./nv/lib/cam/cam_scale.pro
.rnew ./nv/lib/cam/cam_set_body.pro
.rnew ./nv/lib/cam/cam_set_control_points.pro
.rnew ./nv/lib/cam/cam_set_exposure.pro
.rnew ./nv/lib/cam/cam_set_fn_data_p.pro
.rnew ./nv/lib/cam/cam_set_fn_focal_to_image.pro
.rnew ./nv/lib/cam/cam_set_fn_image_to_focal.pro
.rnew ./nv/lib/cam/cam_set_nx.pro
.rnew ./nv/lib/cam/cam_set_ny.pro
.rnew ./nv/lib/cam/cam_set_oaxis.pro
.rnew ./nv/lib/cam/cam_set_poly_matrices.pro
.rnew ./nv/lib/cam/cam_set_scale.pro
.rnew ./nv/lib/class/class_clone_descriptor.pro
.rnew ./nv/lib/class/class_copy_descriptor.pro
.rnew ./nv/lib/class/class_extract.pro
.rnew ./nv/lib/class/class_get_abbrev.pro
.rnew ./nv/lib/class/class_get_field.pro
.rnew ./nv/lib/class/class_get.pro
.rnew ./nv/lib/class/class_insert.pro
.rnew ./nv/lib/class/class_search.pro
.rnew ./nv/lib/class/class_set_field.pro
.rnew ./nv/lib/class/clget.pro
.rnew ./nv/lib/class/clset.pro
.rnew ./nv/lib/cor/cor_add_task.pro
.rnew ./nv/lib/cor/cor_clone_descriptor.pro
.rnew ./nv/lib/cor/cor_copy_descriptor.pro
.rnew ./nv/lib/cor/core_descriptor__define.pro
.rnew ./nv/lib/cor/cor_init_descriptors.pro
.rnew ./nv/lib/cor/cor_name.pro
.rnew ./nv/lib/cor/cor_replicate.pro
.rnew ./nv/lib/cor/cor_set_name.pro
.rnew ./nv/lib/cor/cor_set_udata.pro
.rnew ./nv/lib/cor/cor_tasks.pro
.rnew ./nv/lib/cor/cor_test_udata.pro
.rnew ./nv/lib/cor/cor_udata.pro
.rnew ./nv/lib/cor/cor_user.pro
.rnew ./nv/lib/dsk/disk_descriptor__define.pro
.rnew ./nv/lib/dsk/dsk_body.pro
.rnew ./nv/lib/dsk/dsk_body_to_disk.pro
.rnew ./nv/lib/dsk/dsk_clone_descriptor.pro
.rnew ./nv/lib/dsk/dsk_copy_descriptor.pro
.rnew ./nv/lib/dsk/dsk_disk_to_body.pro
.rnew ./nv/lib/dsk/dsk_dlp.pro
.rnew ./nv/lib/dsk/dsk_ecc.pro
.rnew ./nv/lib/dsk/_dsk_evolve.pro
.rnew ./nv/lib/dsk/dsk_evolve.pro
.rnew ./nv/lib/dsk/dsk_get_ansa.pro
.rnew ./nv/lib/dsk/dsk_get_ap.pro
.rnew ./nv/lib/dsk/dsk_get_disk_points.pro
.rnew ./nv/lib/dsk/dsk_get_dlp.pro
.rnew ./nv/lib/dsk/dsk_get_grid_points.pro
.rnew ./nv/lib/dsk/dsk_get_inc.pro
.rnew ./nv/lib/dsk/dsk_get_inner_disk_points.pro
.rnew ./nv/lib/dsk/dsk_get_inner_radius.pro
.rnew ./nv/lib/dsk/dsk_get_lan.pro
.rnew ./nv/lib/dsk/dsk_get_node.pro
.rnew ./nv/lib/dsk/dsk_get_outer_disk_points.pro
.rnew ./nv/lib/dsk/dsk_get_outer_radius.pro
.rnew ./nv/lib/dsk/dsk_get_radius.pro
.rnew ./nv/lib/dsk/dsk_hide_points.pro
.rnew ./nv/lib/dsk/dsk_init_descriptors.pro
.rnew ./nv/lib/dsk/dsk_intersect_inertial.pro
.rnew ./nv/lib/dsk/dsk_intersect.pro
.rnew ./nv/lib/dsk/dsk_loncor.pro
.rnew ./nv/lib/dsk/dsk_replicate.pro
.rnew ./nv/lib/dsk/dsk_rm_points.pro
.rnew ./nv/lib/dsk/dsk_set_ap.pro
.rnew ./nv/lib/dsk/dsk_set_body.pro
.rnew ./nv/lib/dsk/dsk_set_dapdt.pro
.rnew ./nv/lib/dsk/dsk_set_dlandt.pro
.rnew ./nv/lib/dsk/dsk_set_dlpdt.pro
.rnew ./nv/lib/dsk/dsk_set_dlp.pro
.rnew ./nv/lib/dsk/dsk_set_ecc.pro
.rnew ./nv/lib/dsk/dsk_set_inc.pro
.rnew ./nv/lib/dsk/dsk_set_lan.pro
.rnew ./nv/lib/dsk/dsk_set_sma.pro
.rnew ./nv/lib/dsk/dsk_sma.pro
.rnew ./nv/lib/glb/glb_body.pro
.rnew ./nv/lib/glb/glb_body_to_surface.pro
.rnew ./nv/lib/glb/glb_clone_descriptor.pro
.rnew ./nv/lib/glb/glb_copy_descriptor.pro
.rnew ./nv/lib/glb/_glb_evolve.pro
.rnew ./nv/lib/glb/glb_evolve.pro
.rnew ./nv/lib/glb/glb_get_grid_points.pro
.rnew ./nv/lib/glb/glb_get_limb_points.pro
.rnew ./nv/lib/glb/glb_get_radius.pro
.rnew ./nv/lib/glb/glb_get_surface_normal_body.pro
.rnew ./nv/lib/glb/glb_get_surface_normal.pro
.rnew ./nv/lib/glb/glb_graphic_to_surface.pro
.rnew ./nv/lib/glb/glb_hide_points_limb.pro
.rnew ./nv/lib/glb/glb_hide_points.pro
.rnew ./nv/lib/glb/glb_init_descriptors.pro
.rnew ./nv/lib/glb/glb_intersect_discriminant.pro
.rnew ./nv/lib/glb/glb_intersect_points.pro
.rnew ./nv/lib/glb/glb_intersect.pro
.rnew ./nv/lib/glb/glb_j.pro
.rnew ./nv/lib/glb/glb_lora.pro
.rnew ./nv/lib/glb/glb_lref.pro
.rnew ./nv/lib/glb/glb_mass.pro
.rnew ./nv/lib/glb/glb_nj.pro
.rnew ./nv/lib/glb/glb_radii.pro
.rnew ./nv/lib/glb/glb_replicate.pro
.rnew ./nv/lib/glb/glb_rm_points.pro
.rnew ./nv/lib/glb/glb_set_body.pro
.rnew ./nv/lib/glb/glb_set_j.pro
.rnew ./nv/lib/glb/glb_set_lora.pro
.rnew ./nv/lib/glb/glb_set_lref.pro
.rnew ./nv/lib/glb/glb_set_mass.pro
.rnew ./nv/lib/glb/glb_set_radii.pro
.rnew ./nv/lib/glb/glb_sub_point_graphic.pro
.rnew ./nv/lib/glb/glb_sub_point.pro
.rnew ./nv/lib/glb/glb_surface_normal.pro
.rnew ./nv/lib/glb/glb_surface_to_body.pro
.rnew ./nv/lib/glb/glb_surface_to_graphic.pro
.rnew ./nv/lib/glb/globe_descriptor__define.pro
.rnew ./nv/lib/map/map_center.pro
.rnew ./nv/lib/map/map_clone_descriptor.pro
.rnew ./nv/lib/map/map_condense.pro
.rnew ./nv/lib/map/map_copy_descriptor.pro
.rnew ./nv/lib/map/map_core.pro
.rnew ./nv/lib/map/map_descriptor__define.pro
.rnew ./nv/lib/map/map_ecc.pro
.rnew ./nv/lib/map/map_fn_data_p.pro
.rnew ./nv/lib/map/map_fn_image_to_map.pro
.rnew ./nv/lib/map/map_fn_map_to_image.pro
.rnew ./nv/lib/map/map_image_to_map_mercator.pro
.rnew ./nv/lib/map/map_image_to_map_mollweide.pro
.rnew ./nv/lib/map/map_image_to_map_oblique_disk.pro
.rnew ./nv/lib/map/map_image_to_map_orthographic.pro
.rnew ./nv/lib/map/map_image_to_map.pro
.rnew ./nv/lib/map/map_image_to_map_rectangular.pro
.rnew ./nv/lib/map/map_image_to_map_sinusoidal.pro
.rnew ./nv/lib/map/map_image_to_map_stereographic.pro
.rnew ./nv/lib/map/map_init_descriptors.pro
.rnew ./nv/lib/map/map_lookup_defaults.pro
.rnew ./nv/lib/map/map_lookup_transformations.pro
.rnew ./nv/lib/map/map_map_to_image_mercator.pro
.rnew ./nv/lib/map/map_map_to_image_mollweide.pro
.rnew ./nv/lib/map/map_map_to_image_oblique_disk.pro
.rnew ./nv/lib/map/map_map_to_image_orthographic.pro
.rnew ./nv/lib/map/map_map_to_image.pro
.rnew ./nv/lib/map/map_map_to_image_rectangular.pro
.rnew ./nv/lib/map/map_map_to_image_sinusoidal.pro
.rnew ./nv/lib/map/map_map_to_image_stereographic.pro
.rnew ./nv/lib/map/map_match_type.pro
.rnew ./nv/lib/map/map_origin.pro
.rnew ./nv/lib/map/map_replicate.pro
.rnew ./nv/lib/map/map_scale.pro
.rnew ./nv/lib/map/map_set_center.pro
.rnew ./nv/lib/map/map_set_ecc.pro
.rnew ./nv/lib/map/map_set_fn_data_p.pro
.rnew ./nv/lib/map/map_set_fn_image_to_map.pro
.rnew ./nv/lib/map/map_set_fn_map_to_image.pro
.rnew ./nv/lib/map/map_set_origin.pro
.rnew ./nv/lib/map/map_set_scale.pro
.rnew ./nv/lib/map/map_set_size.pro
.rnew ./nv/lib/map/map_set_type.pro
.rnew ./nv/lib/map/map_set_units.pro
.rnew ./nv/lib/map/map_size.pro
.rnew ./nv/lib/map/map_type.pro
.rnew ./nv/lib/map/map_units.pro
.rnew ./nv/lib/plt/planet_descriptor__define.pro
.rnew ./nv/lib/plt/plt_clone_descriptor.pro
.rnew ./nv/lib/plt/plt_copy_descriptor.pro
.rnew ./nv/lib/plt/_plt_evolve.pro
.rnew ./nv/lib/plt/plt_evolve.pro
.rnew ./nv/lib/plt/plt_globe.pro
.rnew ./nv/lib/plt/plt_init_descriptors.pro
.rnew ./nv/lib/plt/plt_replicate.pro
.rnew ./nv/lib/plt/plt_set_globe.pro
.rnew ./nv/lib/rng/ring_descriptor__define.pro
.rnew ./nv/lib/rng/rng_clone_descriptor.pro
.rnew ./nv/lib/rng/rng_copy_descriptor.pro
.rnew ./nv/lib/rng/rng_disk.pro
.rnew ./nv/lib/rng/_rng_evolve.pro
.rnew ./nv/lib/rng/rng_evolve.pro
.rnew ./nv/lib/rng/rng_init_descriptors.pro
.rnew ./nv/lib/rng/rng_primary.pro
.rnew ./nv/lib/rng/rng_replicate.pro
.rnew ./nv/lib/rng/rng_set_disk.pro
.rnew ./nv/lib/rng/rng_set_primary.pro
.rnew ./nv/lib/str/star_descriptor__define.pro
.rnew ./nv/lib/str/str_clone_descriptor.pro
.rnew ./nv/lib/str/str_copy_descriptor.pro
.rnew ./nv/lib/str/_str_evolve.pro
.rnew ./nv/lib/str/str_evolve.pro
.rnew ./nv/lib/str/str_get_mag.pro
.rnew ./nv/lib/str/str_globe.pro
.rnew ./nv/lib/str/str_init_descriptors.pro
.rnew ./nv/lib/str/str_limit_mag.pro
.rnew ./nv/lib/str/str_lum.pro
.rnew ./nv/lib/str/str_replicate.pro
.rnew ./nv/lib/str/str_set_globe.pro
.rnew ./nv/lib/str/str_set_lum.pro
.rnew ./nv/lib/str/str_set_sp.pro
.rnew ./nv/lib/str/str_sp.pro
.rnew ./nv/lib/tools/add_core_task.pro
.rnew ./nv/lib/tools/composite/body_to_disk.pro
.rnew ./nv/lib/tools/composite/body_to_disk_solar.pro
.rnew ./nv/lib/tools/composite/body_to_image_pos.pro
.rnew ./nv/lib/tools/composite/disk_to_body.pro
.rnew ./nv/lib/tools/composite/disk_to_body_ref.pro
.rnew ./nv/lib/tools/composite/disk_to_body_solar.pro
.rnew ./nv/lib/tools/composite/disk_to_image.pro
.rnew ./nv/lib/tools/composite/disk_to_map.pro
.rnew ./nv/lib/tools/composite/dlon_to_daz.pro
.rnew ./nv/lib/tools/composite/image_to_disk.pro
.rnew ./nv/lib/tools/composite/image_to_inertial.pro
.rnew ./nv/lib/tools/composite/image_to_orbit.pro
.rnew ./nv/lib/tools/composite/image_to_radec.pro
.rnew ./nv/lib/tools/composite/image_to_surface.pro
.rnew ./nv/lib/tools/composite/inertial_to_disk_pos.pro
.rnew ./nv/lib/tools/composite/inertial_to_disk.pro
.rnew ./nv/lib/tools/composite/inertial_to_image_pos.pro
.rnew ./nv/lib/tools/composite/inertial_to_image.pro
.rnew ./nv/lib/tools/composite/map_to_disk.pro
.rnew ./nv/lib/tools/composite/map_to_surface.pro
.rnew ./nv/lib/tools/composite/radec_to_image.pro
.rnew ./nv/lib/tools/composite/surface_to_image.pro
.rnew ./nv/lib/tools/composite/surface_to_map.pro
.rnew ./nv/lib/tools/dsk_intersect_lt.pro
.rnew ./nv/lib/tools/dsk_radial_resolution.pro
.rnew ./nv/lib/tools/get_body_time.pro
.rnew ./nv/lib/tools/get_core_name.pro
.rnew ./nv/lib/tools/get_core_tasks.pro
.rnew ./nv/lib/tools/get_core_user.pro
.rnew ./nv/lib/tools/get_disk_ref.pro
.rnew ./nv/lib/tools/get_ring_profile_bin.pro
.rnew ./nv/lib/tools/get_ring_profile_n.pro
.rnew ./nv/lib/tools/get_ring_profile_outline.pro
.rnew ./nv/lib/tools/get_ring_profile.pro
.rnew ./nv/lib/tools/get_solar_ref.pro
.rnew ./nv/lib/tools/illumination_fraction.pro
.rnew ./nv/lib/tools/image_azimuth_pos.pro
.rnew ./nv/lib/tools/image_azimuth.pro
.rnew ./nv/lib/tools/image_celestial_northangle.pro
.rnew ./nv/lib/tools/image_dlon.pro
.rnew ./nv/lib/tools/image_northangle.pro
.rnew ./nv/lib/tools/image_predict_orbit.pro
.rnew ./nv/lib/tools/image_predict.pro
.rnew ./nv/lib/tools/image_predict_wind.pro
.rnew ./nv/lib/tools/impact_param.pro
.rnew ./nv/lib/tools/in_image.pro
.rnew ./nv/lib/tools/move_points.pro
.rnew ./nv/lib/tools/orb/orb_anom_to_arg.pro
.rnew ./nv/lib/tools/orb/orb_anom_to_lon.pro
.rnew ./nv/lib/tools/orb/orb_arg_to_anom.pro
.rnew ./nv/lib/tools/orb/orb_arg_to_lon.pro
.rnew ./nv/lib/tools/orb/orb_compute_dapdt.pro
.rnew ./nv/lib/tools/orb/orb_compute_dlandt.pro
.rnew ./nv/lib/tools/orb/orb_compute_dmadt.pro
.rnew ./nv/lib/tools/orb/orb_compute_dmldt.pro
.rnew ./nv/lib/tools/orb/orb_compute_elements.pro
.rnew ./nv/lib/tools/orb/orb_construct_descriptor.pro
.rnew ./nv/lib/tools/orb/orb_evolve_ma.pro
.rnew ./nv/lib/tools/orb/orb_evolve.pro
.rnew ./nv/lib/tools/orb/orb_get_ap.pro
.rnew ./nv/lib/tools/orb/orb_get_ascending_node.pro
.rnew ./nv/lib/tools/orb/orb_get_dapdt.pro
.rnew ./nv/lib/tools/orb/orb_get_dlandt.pro
.rnew ./nv/lib/tools/orb/orb_get_dmadt.pro
.rnew ./nv/lib/tools/orb/orb_get_dmldt.pro
.rnew ./nv/lib/tools/orb/orb_get_ecc.pro
.rnew ./nv/lib/tools/orb/orb_get_inc.pro
.rnew ./nv/lib/tools/orb/orb_get_lan.pro
.rnew ./nv/lib/tools/orb/orb_get_ma.pro
.rnew ./nv/lib/tools/orb/orb_get_sma.pro
.rnew ./nv/lib/tools/orb/orb_inertialize.pro
.rnew ./nv/lib/tools/orb/orb_lon_to_anom.pro
.rnew ./nv/lib/tools/orb/orb_lon_to_arg.pro
.rnew ./nv/lib/tools/orb/orb_plot.pro
.rnew ./nv/lib/tools/orb/orb_print_descriptor.pro
.rnew ./nv/lib/tools/orb/orb_set_ap.pro
.rnew ./nv/lib/tools/orb/orb_set_dapdt.pro
.rnew ./nv/lib/tools/orb/orb_set_dlandt.pro
.rnew ./nv/lib/tools/orb/orb_set_dmadt.pro
.rnew ./nv/lib/tools/orb/orb_set_ecc.pro
.rnew ./nv/lib/tools/orb/orb_set_inc.pro
.rnew ./nv/lib/tools/orb/orb_set_lan.pro
.rnew ./nv/lib/tools/orb/orb_set_ma.pro
.rnew ./nv/lib/tools/orb/orb_set_sma.pro
.rnew ./nv/lib/tools/orb/orb_solve_kepler.pro
.rnew ./nv/lib/tools/orb/orb_test.pro
.rnew ./nv/lib/tools/orb/orb_to_cartesian.pro
.rnew ./nv/lib/tools/phase_correction.pro
.rnew ./nv/lib/tools/photometry/emission_angle.pro
.rnew ./nv/lib/tools/photometry/incidence_angle.pro
.rnew ./nv/lib/tools/photometry/local_vertical.pro
.rnew ./nv/lib/tools/photometry/phase_angle.pro
.rnew ./nv/lib/tools/photometry/photometric_angles.pro
.rnew ./nv/lib/tools/pht/pht_angles.pro
.rnew ./nv/lib/tools/pht/pht_lunar_lambert.pro
.rnew ./nv/lib/tools/pht/pht_lunar.pro
.rnew ./nv/lib/tools/pht/pht_minneart.pro
.rnew ./nv/lib/tools/plot_inertial.pro
.rnew ./nv/lib/tools/project_map.pro
.rnew ./nv/lib/tools/radec_grid.pro
.rnew ./nv/lib/tools/reproject_image.pro
.rnew ./nv/lib/tools/set_core_name.pro
.rnew ./nv/lib/tools/stellab_pos.pro
.rnew ./nv/lib/tools/stellab.pro
.rnew ./nv/lib/tools/stellab_radec.pro
.rnew ./nv/lib/tools/sub_latlon.pro
.rnew ./nv/lib/tools/surface_to_degrees.pro
.rnew ./nv/lib/tools/synth_image.pro
.rnew ./nv/lib/tools/warp_cp.pro
.rnew ./nv/sys/data_descriptor__define.pro
.rnew ./nv/sys/keyval_struct__define.pro
.rnew ./nv/sys/lic/get_tokens-old.pro
.rnew ./nv/sys/lic/get_tokens.pro
.rnew ./nv/sys/lic/it_solve.pro
.rnew ./nv/sys/lic/lic_filename.pro
.rnew ./nv/sys/lic/lic_gethost.pro
.rnew ./nv/sys/lic/lic_probe.pro
.rnew ./nv/sys/lic/lic_read.pro
.rnew ./nv/sys/lic/lic_tamper.pro
.rnew ./nv/sys/lic/lic_validate.pro
.rnew ./nv/sys/lic/lic_validate_pwd.pro
.rnew ./nv/sys/lic/maxz.pro
.rnew ./nv/sys/lic/optimize_2d.pro
.rnew ./nv/sys/lic/shape1.pro
.rnew ./nv/sys/lic/s_tree.pro
.rnew ./nv/sys/lic/tvhash.pro
.rnew ./nv/sys/nv_add_transient_keyvals.pro
.rnew ./nv/sys/nv_clone_descriptor.pro
.rnew ./nv/sys/nv_compress_events.pro
.rnew ./nv/sys/nv_copy_descriptor.pro
.rnew ./nv/sys/nv_data.pro
.rnew ./nv/sys/nv_dereference.pro
.rnew ./nv/sys/nv_detect_filetype.pro
.rnew ./nv/sys/nv_detect_instrument.pro
.rnew ./nv/sys/nv_event_struct__define.pro
.rnew ./nv/sys/nv_extract_idp.pro
.rnew ./nv/sys/nv_extract_sn.pro
.rnew ./nv/sys/nv_flush.pro
.rnew ./nv/sys/nv_free.pro
.rnew ./nv/sys/nv_free_udata.pro
.rnew ./nv/sys/nv_get_sn.pro
.rnew ./nv/sys/nv_get_value.pro
.rnew ./nv/sys/nv_header.pro
.rnew ./nv/sys/nv_help.pro
.rnew ./nv/sys/nv_id_string.pro
.rnew ./nv/sys/nv_init_descriptor.pro
.rnew ./nv/sys/nv_instrument.pro
.rnew ./nv/sys/nv_lookup_io.pro
.rnew ./nv/sys/nv_lookup_translators.pro
.rnew ./nv/sys/nv_message.pro
.rnew ./nv/sys/nv_notify_list_struct__define.pro
.rnew ./nv/sys/nv_notify.pro
.rnew ./nv/sys/nv_notify_register.pro
.rnew ./nv/sys/nv_notify_unregister.pro
.rnew ./nv/sys/nv_parse_keyval.pro
.rnew ./nv/sys/nv_parse_keyvals.pro
.rnew ./nv/sys/nv_parse_transient_keyvals.pro
.rnew ./nv/sys/nv_put_value.pro
.rnew ./nv/sys/nv_read_config.pro
.rnew ./nv/sys/nv_read.pro
.rnew ./nv/sys/nv_replicate.pro
.rnew ./nv/sys/nv_rereference.pro
.rnew ./nv/sys/nv_reset.pro
.rnew ./nv/sys/nv_resume_events.pro
.rnew ./nv/sys/nv_set_data.pro
.rnew ./nv/sys/nv_set_header.pro
.rnew ./nv/sys/nv_set_udata.pro
.rnew ./nv/sys/nv_state_struct__define.pro
.rnew ./nv/sys/nv_suspend_events.pro
.rnew ./nv/sys/nv_udata.pro
.rnew ./nv/sys/nv_write.pro
.rnew ./nv/sys/tr_keyword_value.pro
.rnew ./util/abbrev/h.pro
.rnew ./util/abbrev/p.pro
.rnew ./util/abbrev/pt.pro
.rnew ./util/abbrev/tr.pro
.rnew ./util/activity.pro
.rnew ./util/append_array.pro
.rnew ./util/arrcat.pro
.rnew ./util/arrtrim.pro
.rnew ./util/b1950_to_j2000.pro
.rnew ./util/byte_to_bit.pro
.rnew ./util/capture_png.pro
.rnew ./util/cat_points.pro
.rnew ./util/cat_vectors.pro
.rnew ./util/c_correlate_2d.pro
.rnew ./util/cc_threshold.pro
.rnew ./util/centric_to_graphic.pro
.rnew ./util/clip.pro
.rnew ./util/cntrd.pro
.rnew ./util/collapse_array.pro
.rnew ./util/colormap/apply_colormap.pro
.rnew ./util/colormap/colormap_descriptor__define.pro
.rnew ./util/colormap/colormap_descriptor.pro
.rnew ./util/colormap/compute_colormap.pro
.rnew ./util/combine_duplicate_points.pro
.rnew ./util/complement.pro
.rnew ./util/compress_list.pro
.rnew ./util/contiguous.pro
.rnew ./util/correlate_pairs.pro
.rnew ./util/correlate_points.pro
.rnew ./util/covariance.pro
.rnew ./util/cr_correlation.pro
.rnew ./util/cross_compare.pro
.rnew ./util/ct/ctblack.pro
.rnew ./util/ct/ctblue.pro
.rnew ./util/ct/ctcyan.pro
.rnew ./util/ct/ctgreen.pro
.rnew ./util/ct/ctlookup.pro
.rnew ./util/ct/ctmod.pro
.rnew ./util/ct/ctpurple.pro
.rnew ./util/ct/ctred.pro
.rnew ./util/ct/ctwhite.pro
.rnew ./util/ct/ctyellow.pro
.rnew ./util/cursor_move.pro
.rnew ./util/cw__form.pro
.rnew ./util/ddmmmyyyy_to_jd.pro
.rnew ./util/decrapify.pro
.rnew ./util/defined.pro
.rnew ./util/defval.pro
.rnew ./util/degen.pro
.rnew ./util/deg_to_degmmss.pro
.rnew ./util/deg_to_hhmmss.pro
.rnew ./util/delete_file.pro
.rnew ./util/despike.pro
.rnew ./util/device_cursor_scan.pro
.rnew ./util/dir_rep.pro
.rnew ./util/dropouts.pro
.rnew ./util/d_undefined.pro
.rnew ./util/enigma.pro
.rnew ./util/epoch_dt.pro
.rnew ./util/external_points.pro
.rnew ./util/extract_doc.pro
.rnew ./util/fdelete.pro
.rnew ./util/fill_array.pro
.rnew ./util/findfile1.pro
.rnew ./util/findfiles.pro
.rnew ./util/fixed_array.pro
.rnew ./util/flatten_bg.pro
.rnew ./util/gauss2d_fit.pro
.rnew ./util/gauss_2d.pro
.rnew ./util/gaussfit2d_linear.pro
.rnew ./util/gaussfit_linear.pro
.rnew ./util/gen/colgen.pro
.rnew ./util/gen/diaggen.pro
.rnew ./util/gen/gen3x.pro
.rnew ./util/gen/gen3y.pro
.rnew ./util/gen/gen3z.pro
.rnew ./util/gen/linegen3x.pro
.rnew ./util/gen/linegen3y.pro
.rnew ./util/gen/linegen3z.pro
.rnew ./util/gen/mxgen.pro
.rnew ./util/gen/selgen.pro
.rnew ./util/gen/vecgen.pro
.rnew ./util/gen/wrong_selgen.pro
.rnew ./util/get_doc_purpose.pro
.rnew ./util/gethost.pro
.rnew ./util/get_juliandate.pro
.rnew ./util/get_mem.pro
.rnew ./util/get_username.pro
.rnew ./util/graphic_to_centric.pro
.rnew ./util/grid_correlate.pro
.rnew ./util/hist__2d.pro
.rnew ./util/icv/edge_model_atan.pro
.rnew ./util/icv/edge_model_gauss.pro
.rnew ./util/icv/edge_model_nav_limb.pro
.rnew ./util/icv/edge_model_nav_ring.pro
.rnew ./util/icv/icv_chisq.pro
.rnew ./util/icv/icv_coeff.pro
.rnew ./util/icv/icv_compute_directions.pro
.rnew ./util/icv/icv_convert_scan_offsets.pro
.rnew ./util/icv/icv_reset_scan_precision.pro
.rnew ./util/icv/icv_scan_strip.pro
.rnew ./util/icv/icv_strip_curve.pro
.rnew ./util/idl_obsolete/a_correlate.pro
.rnew ./util/idl_obsolete/adapt_hist_equal.pro
.rnew ./util/idl_obsolete/addsysvar.pro
.rnew ./util/idl_obsolete/adjct.pro
.rnew ./util/idl_obsolete/amoeba.pro
.rnew ./util/idl_obsolete/annotate.pro
.rnew ./util/idl_obsolete/anova.pro
.rnew ./util/idl_obsolete/anova_unequal.pro
.rnew ./util/idl_obsolete/array_indices.pro
.rnew ./util/idl_obsolete/arrow.pro
.rnew ./util/idl_obsolete/ascii_template.pro
.rnew ./util/idl_obsolete/bar_plot.pro
.rnew ./util/idl_obsolete/betai.pro
.rnew ./util/idl_obsolete/beta.pro
.rnew ./util/idl_obsolete/bilinear.pro
.rnew ./util/idl_obsolete/binary_template.pro
.rnew ./util/idl_obsolete/bin_date.pro
.rnew ./util/idl_obsolete/binomial.pro
.rnew ./util/idl_obsolete/bisect_pdf.pro
.rnew ./util/idl_obsolete/blk_con.pro
.rnew ./util/idl_obsolete/box_cursor.pro
.rnew ./util/idl_obsolete/caldat.pro
.rnew ./util/idl_obsolete/calendar.pro
.rnew ./util/idl_obsolete/c_correlate.pro
.rnew ./util/idl_obsolete/cdf_exists.pro
.rnew ./util/idl_obsolete/c_edit.pro
.rnew ./util/idl_obsolete/chebyshev.pro
.rnew ./util/idl_obsolete/chi_sqr1.pro
.rnew ./util/idl_obsolete/chisqr_cvf.pro
.rnew ./util/idl_obsolete/chisqr_pdf.pro
.rnew ./util/idl_obsolete/chi_sqr.pro
.rnew ./util/idl_obsolete/cir_3pnt.pro
.rnew ./util/idl_obsolete/cluster.pro
.rnew ./util/idl_obsolete/clust_wts.pro
.rnew ./util/idl_obsolete/color_edit.pro
.rnew ./util/idl_obsolete/colormap_applicable.pro
.rnew ./util/idl_obsolete/comfit.pro
.rnew ./util/idl_obsolete/complexround.pro
.rnew ./util/idl_obsolete/cond.pro
.rnew ./util/idl_obsolete/congrid.pro
.rnew ./util/idl_obsolete/contingent.pro
.rnew ./util/idl_obsolete/convert_sr54.pro
.rnew ./util/idl_obsolete/coord2to3.pro
.rnew ./util/idl_obsolete/correlate.pro
.rnew ./util/idl_obsolete/correl_matrix.pro
.rnew ./util/idl_obsolete/cosines.pro
.rnew ./util/idl_obsolete/cramer.pro
.rnew ./util/idl_obsolete/create_view.pro
.rnew ./util/idl_obsolete/crossp.pro
.rnew ./util/idl_obsolete/crvlength.pro
.rnew ./util/idl_obsolete/cti_test.pro
.rnew ./util/idl_obsolete/ct_luminance.pro
.rnew ./util/idl_obsolete/curvefit.pro
.rnew ./util/idl_obsolete/cv_coord.pro
.rnew ./util/idl_obsolete/cvttobm.pro
.rnew ./util/idl_obsolete/cw_animate.pro
.rnew ./util/idl_obsolete/cw_arcball.pro
.rnew ./util/idl_obsolete/cw_bgroup.pro
.rnew ./util/idl_obsolete/cw_bselector.pro
.rnew ./util/idl_obsolete/cw_clr_index.pro
.rnew ./util/idl_obsolete/cw_color_index.pro
.rnew ./util/idl_obsolete/cw_colorsel.pro
.rnew ./util/idl_obsolete/cw_defroi.pro
.rnew ./util/idl_obsolete/cw_dice.pro
.rnew ./util/idl_obsolete/cw_field.pro
.rnew ./util/idl_obsolete/cw_filesel.pro
.rnew ./util/idl_obsolete/cw_form.pro
.rnew ./util/idl_obsolete/cw_fslider.pro
.rnew ./util/idl_obsolete/cw_light_editor.pro
.rnew ./util/idl_obsolete/cw_loadstate.pro
.rnew ./util/idl_obsolete/cw_orient.pro
.rnew ./util/idl_obsolete/cw_palette_editor.pro
.rnew ./util/idl_obsolete/cw_pdmenu.pro
.rnew ./util/idl_obsolete/cw_rgbslider.pro
.rnew ./util/idl_obsolete/cw_savestate.pro
.rnew ./util/idl_obsolete/cw_tmpl.pro
.rnew ./util/idl_obsolete/cw_treestructure.pro
.rnew ./util/idl_obsolete/cw_zoom.pro
.rnew ./util/idl_obsolete/define_msgblk_from_file.pro
.rnew ./util/idl_obsolete/defroi.pro
.rnew ./util/idl_obsolete/demo_mode.pro
.rnew ./util/idl_obsolete/deriv.pro
.rnew ./util/idl_obsolete/derivsig.pro
.rnew ./util/idl_obsolete/determ.pro
.rnew ./util/idl_obsolete/dialog_read_image.pro
.rnew ./util/idl_obsolete/dialog_write_image.pro
.rnew ./util/idl_obsolete/diffeq_23.pro
.rnew ./util/idl_obsolete/diffeq_45.pro
.rnew ./util/idl_obsolete/digital_filter.pro
.rnew ./util/idl_obsolete/disp_txt.pro
.rnew ./util/idl_obsolete/dissolve.pro
.rnew ./util/idl_obsolete/dist.pro
.rnew ./util/idl_obsolete/eigen_ii.pro
.rnew ./util/idl_obsolete/eigenql.pro
.rnew ./util/idl_obsolete/eigenvec.pro
.rnew ./util/idl_obsolete/eos_exists.pro
.rnew ./util/idl_obsolete/eos_gd_query.pro
.rnew ./util/idl_obsolete/eos_pt_query.pro
.rnew ./util/idl_obsolete/eos_query.pro
.rnew ./util/idl_obsolete/eos_sw_query.pro
.rnew ./util/idl_obsolete/equal_variance.pro
.rnew ./util/idl_obsolete/errplot.pro
.rnew ./util/idl_obsolete/expand.pro
.rnew ./util/idl_obsolete/extrac.pro
.rnew ./util/idl_obsolete/extract_slice.pro
.rnew ./util/idl_obsolete/factorial.pro
.rnew ./util/idl_obsolete/f_cvf.pro
.rnew ./util/idl_obsolete/filepath.pro
.rnew ./util/idl_obsolete/file_which.pro
.rnew ./util/idl_obsolete/fillcontour.pro
.rnew ./util/idl_obsolete/flick.pro
.rnew ./util/idl_obsolete/flow3.pro
.rnew ./util/idl_obsolete/funct.pro
.rnew ./util/idl_obsolete/fv_test.pro
.rnew ./util/idl_obsolete/fx_root.pro
.rnew ./util/idl_obsolete/gamma_ct.pro
.rnew ./util/idl_obsolete/gamma.pro
.rnew ./util/idl_obsolete/gauss2dfit.pro
.rnew ./util/idl_obsolete/gauss_cvf.pro
.rnew ./util/idl_obsolete/gaussfit.pro
.rnew ./util/idl_obsolete/gauss_pdf.pro
.rnew ./util/idl_obsolete/gauss.pro
.rnew ./util/idl_obsolete/goodfit.pro
.rnew ./util/idl_obsolete/hanning.pro
.rnew ./util/idl_obsolete/h_eq_ct.pro
.rnew ./util/idl_obsolete/h_eq_int.pro
.rnew ./util/idl_obsolete/hilbert.pro
.rnew ./util/idl_obsolete/hist_2d.pro
.rnew ./util/idl_obsolete/hist_equal_ct.pro
.rnew ./util/idl_obsolete/hist_equal_int.pro
.rnew ./util/idl_obsolete/hist_equal.pro
.rnew ./util/idl_obsolete/identity.pro
.rnew ./util/idl_obsolete/image_cont.pro
.rnew ./util/idl_obsolete/insget.pro
.rnew ./util/idl_obsolete/insput.pro
.rnew ./util/idl_obsolete/insvis.pro
.rnew ./util/idl_obsolete/interpol.pro
.rnew ./util/idl_obsolete/join.pro
.rnew ./util/idl_obsolete/julday.pro
.rnew ./util/idl_obsolete/krig2d.pro
.rnew ./util/idl_obsolete/kruskal_wallis.pro
.rnew ./util/idl_obsolete/kurtosis.pro
.rnew ./util/idl_obsolete/laguerre.pro
.rnew ./util/idl_obsolete/linfit.pro
.rnew ./util/idl_obsolete/loadct.pro
.rnew ./util/idl_obsolete/lu_complex.pro
.rnew ./util/idl_obsolete/maketree.pro
.rnew ./util/idl_obsolete/matrix_power.pro
.rnew ./util/idl_obsolete/m_correlate.pro
.rnew ./util/idl_obsolete/md_test.pro
.rnew ./util/idl_obsolete/meanabsdev.pro
.rnew ./util/idl_obsolete/mean.pro
.rnew ./util/idl_obsolete/mk_library_help.pro
.rnew ./util/idl_obsolete/modifyct.pro
.rnew ./util/idl_obsolete/moment.pro
.rnew ./util/idl_obsolete/mp_basic.pro
.rnew ./util/idl_obsolete/mpeg_close.pro
.rnew ./util/idl_obsolete/mpeg_open.pro
.rnew ./util/idl_obsolete/mpeg_put.pro
.rnew ./util/idl_obsolete/mpeg_save.pro
.rnew ./util/idl_obsolete/mp_widgets.pro
.rnew ./util/idl_obsolete/multicompare.pro
.rnew ./util/idl_obsolete/multi.pro
.rnew ./util/idl_obsolete/ncdf_exists.pro
.rnew ./util/idl_obsolete/norm.pro
.rnew ./util/idl_obsolete/nr_elmhes.pro
.rnew ./util/idl_obsolete/nr_hqr.pro
.rnew ./util/idl_obsolete/nr_lubksb.pro
.rnew ./util/idl_obsolete/nr_ludcmp.pro
.rnew ./util/idl_obsolete/nr_mprove.pro
.rnew ./util/idl_obsolete/nr_sprsin.pro
.rnew ./util/idl_obsolete/nr_svbksb.pro
.rnew ./util/idl_obsolete/nr_svd.pro
.rnew ./util/idl_obsolete/nr_wtn.pro
.rnew ./util/idl_obsolete/online_help_pdf_nd2file.pro
.rnew ./util/idl_obsolete/only_8bit.pro
.rnew ./util/idl_obsolete/oploterr.pro
.rnew ./util/idl_obsolete/pairwise.pro
.rnew ./util/idl_obsolete/palette.pro
.rnew ./util/idl_obsolete/partial2_cor.pro
.rnew ./util/idl_obsolete/partial_cor.pro
.rnew ./util/idl_obsolete/path_sep.pro
.rnew ./util/idl_obsolete/pcomp.pro
.rnew ./util/idl_obsolete/p_correlate.pro
.rnew ./util/idl_obsolete/pd_bisection.pro
.rnew ./util/idl_obsolete/pde_adi.pro
.rnew ./util/idl_obsolete/phaser.pro
.rnew ./util/idl_obsolete/pickfile.pro
.rnew ./util/idl_obsolete/plot_3dbox.pro
.rnew ./util/idl_obsolete/ploterr.pro
.rnew ./util/idl_obsolete/plot_field.pro
.rnew ./util/idl_obsolete/pmf.pro
.rnew ./util/idl_obsolete/pm.pro
.rnew ./util/idl_obsolete/pnt_line.pro
.rnew ./util/idl_obsolete/polar_contour.pro
.rnew ./util/idl_obsolete/polar_surface.pro
.rnew ./util/idl_obsolete/poly_area.pro
.rnew ./util/idl_obsolete/polycontour.pro
.rnew ./util/idl_obsolete/poly_fit.pro
.rnew ./util/idl_obsolete/polyfitw.pro
.rnew ./util/idl_obsolete/p
