.rnew ext_get_name.pro
.rnew ext_read_bmp.pro
.rnew ext_read_jpeg.pro
.rnew ext_read_jpg.pro
.rnew ext_read_pict.pro
.rnew ext_read_png.pro
.rnew ext_read_tiff.pro
.rnew ext_read_tif.pro
.rnew ext_read_x11.pro
.rnew ext_read_xwd.pro
.rnew read_ext.pro
