.rnew star_descriptor__define.pro
.rnew str_copy_descriptor.pro
.rnew _str_evolve.pro
.rnew str_evolve.pro
.rnew str_get_mag.pro
.rnew str_globe.pro
.rnew str_init_descriptors.pro
.rnew str_limit_mag.pro
.rnew str_lum.pro
.rnew str_replicate.pro
.rnew str_set_globe.pro
.rnew str_set_lum.pro
.rnew str_set_sp.pro
.rnew str_sp.pro
