.rnew v_angle.pro
.rnew v_cross.pro
.rnew v_inner.pro
.rnew v_mag.pro
.rnew v_mean.pro
.rnew v_median.pro
.rnew v_mxm.pro
.rnew v_rotate_11.pro
.rnew v_rotate.pro
.rnew v_sample.pro
.rnew v_sqmag.pro
.rnew v_stdev.pro
.rnew v_transform_forward.pro
.rnew v_transform_reverse.pro
.rnew v_unit.pro
