pro grim_compile
;@grim_bitmaps.include
grim_bitmaps_include
;@grim_util.include
grim_util_include
;@grim_planes.include
grim_planes_include
;@grim_data.include
grim_data_include
;@grim_user.include
grim_user_include
;@grim_compute.include
grim_compute_include
;@grim_overlays.include
grim_overlays_include
;@grim_descriptors.include
grim_descriptors_include
;@grim_image.include
grim_image_include
grim_deps
end
