#!/usr/bin/env bash
# We recommend you do not edit this file
# It is automatically generated and overwritten by OMINAS' configure.sh
# If you need to add commands to be executed before starting OMINAS,
# we suggest placing them either in your ~/.bashrc or ~/.profile (in
# which case they will be executed before ~/.ominas/ominas_setup.sh), or
# in ~/.ominas/ominas_postsetup.sh (which is executed after ~/.ominas/ominas_setup.sh, 
# thus it can make use of other OMINAS variables).
# ~/.ominas/ominas_setup.sh is never overwritten by configure.sh



#------------------------------------------------------------------------------#
# command-line arguments
#
#  :<VAR>=<VAL>   Set environment variable VAR to value VAL.
#  ::<VAR>	  Set environment variable VAR to 1.
#  --<var>        Set ominas shell argument var to '0' (by ominas_value).
#  ++<var>        Set ominas shell argument var to '1' (by ominas_value).
#  <var>==<val>   Set ominas shell argument var to value val (by ominas_value).	
#
#------------------------------------------------------------------------------#
args+=$HOME/.ominas/ominas_startup.bat
for arg in $@; do
 if [[ $arg == ++* ]] ; then _args+=($arg)
 elif [[ $arg == --* ]] ; then _args+=($arg)
 elif [[ $arg == *==* ]] ; then _args+=($arg)
 elif [[ $arg == ::* ]] ; then _env=${arg:2:127}
 elif [[ $arg == :* ]] ; then export ${arg:1:127}
 else args+=($arg)
 fi
 if [[ $_env != "" ]] ; 
  then 
    export ${_env}=1
  fi
done
args+=(\-args)
args+=(${_args[*]})


#------------------------------------------------------------------------------#
# set up environment
#------------------------------------------------------------------------------#
. /home/spitale/.ominas/ominas_setup.sh



#------------------------------------------------------------------------------#
# setup ominas and ominasde
#------------------------------------------------------------------------------#
