.rnew dd_add.pro
.rnew dd_div.pro
.rnew dd_errsum.pro
.rnew dd_mult_d_dd.pro
.rnew dd_mult_dd_d.pro
.rnew dd_mult.pro
.rnew dd_neg.pro
.rnew dd_prod.pro
.rnew dd_quick_two_sum.pro
.rnew dd_quotient.pro
.rnew dd_real.pro
.rnew dd_reduce.pro
.rnew dd_renorm.pro
.rnew dd_split.pro
.rnew dd_square.pro
.rnew dd_two_prod.pro
.rnew dd_two_sum.pro
.rnew doubledouble__define.pro
